name = "ID2202 Autograder"
version = "3"

# All paths are relative to this file, not where the binary is being run from.

# Logging settings
[log]
dir = "./data/logs" # where to place generated logs
verbose = false     # whether to output debug messages

# Entrypoint monitor process settings
[monitor]
poll_interval_seconds = 30

# Process notification settings
[notify]
poll_timeout_millisec = 5000

# Configuration for incoming submissions
[submission]
max_tag_length = 128
max_payload = 65536
comment_signature = "(_This is an automated response from the autograder_ \U0001F916)"

# Information about GitHub instances that can submit grading jobs
[submission.github]
webhook_secret = "s3cr3t"

# Known GitHub servers that we can accept requests from
[[submission.github.known_instances]]
domain = "gits-15.sys.kth.se"
auth_token = "ChangeMe"
allowed_orgs = ["ID2202-jwikman-test"]
allowed_repo_prefixes = ["id2202-"]
allowed_repo_suffixes = []
prohibited_repo_prefixes = []
prohibited_repo_suffixes = ["-shadow"]

# Information about GitLab instances that can submit grading jobs
[submission.gitlab]
webhook_secret = "s3cr3t"

# Known GitLab instances that we can accept requests from
[[submission.gitlab.known_instances]]
domain = "localhost:8929"
auth_token = "ChangeMe"
allowed_namespaces = ["id2202-test", "id2202-2025-testing"]
allowed_repo_prefixes = ["id2202-"]
allowed_repo_suffixes = []
prohibited_repo_prefixes = []
prohibited_repo_suffixes = []
use_https = false

# Postgres configuration
[postgres]
user = "autograder"
password = "ChangeMe"
host = "127.0.0.1"
port = 5432

# Server-specific configuration
[server]
address = "127.0.0.1" # this only works outside containers
port = 8080

# Secrets that allow external entities to access information
[server.secrets]
api_auth_tokens = []

# Runner-specific configuration
[runner]
n_runners = 4
database_poll_interval_seconds = 10
podman_image = "docker.io/johnwikman/id2202:0.3.0"
podman_network_prefix = "id2202_runnernet"

# Only ever mount the input files, never expose the intended code or
# output to the running program. That is checked outside the solutions
# execution environment.
mount_repo = "/id2202/repo"
mount_tests = "/id2202/tests"

workspace_dir = "./data/workspace" # storage for data currently being worked on
shadow_dir = "./data/shadow"       # storage for submitted solutions
test_config = "./tests/tests.toml" # configuration for test cases

# Settings for markdown output during reporting.
[reporting.markdown]
symbol_ok = "\u2705"             # ✅
symbol_skipped = "\u2753"        # ❓
symbol_failed = "\u274C"         # ❌
symbol_tagsuccess = "\U0001F389" # 🎉
symbol_build = "\U0001F6A7"      # 🚧
show_indicator_submission_header = false
show_indicator_tag_header = true
truncate_len = 2000
