use serde::Deserialize;
use static_files::resource_dir;
use std::env;
use std::path::Path;

fn main() -> std::io::Result<()> {
    let out_dir = env::var("OUT_DIR").unwrap();

    let mut rd = resource_dir("./web/static");
    rd.with_generated_filename(Path::new(&out_dir).join("generated_web_static.rs"));
    rd.build()?;

    generate_cdn_cache(&out_dir);

    Ok(())
}

#[derive(Deserialize)]
struct CDNBom {
    asset: Vec<CDNBomAsset>,
}
/// One `[[asset]]` in `web/cdncache/bom.toml`.
#[derive(Deserialize)]
struct CDNBomAsset {
    sources: Vec<String>,
    target: String,
    sha384: String,
    served_as: String,
}

/// Generates "generated_cdn_cache.rs" based on "web/cdncache/bom.toml". The
/// generated file contains a `CDN_FILES` constant that defines each asset, how
/// it shall be served, and its data, plus a `resources()` function returning the
/// same assets as a map that `ResourceFiles` can serve directly.
fn generate_cdn_cache(out_dir: &str) {
    let cache_dir = Path::new(&env::var("CARGO_MANIFEST_DIR").unwrap()).join("web/cdncache");
    let bom_path = cache_dir.join("bom.toml");
    println!("cargo:rerun-if-changed={}", bom_path.display());

    // Helper functions
    fn sha384(bytes: &[u8]) -> String {
        use base64::{engine::general_purpose::STANDARD, Engine};
        use sha2::{Digest, Sha384};
        STANDARD.encode(Sha384::digest(bytes))
    }
    fn download(sources: &[String]) -> Vec<u8> {
        for url in sources {
            if let Ok(bytes) = reqwest::blocking::get(url)
                .and_then(|r| r.error_for_status())
                .and_then(|r| r.bytes())
            {
                return bytes.to_vec();
            }
        }
        panic!("could not download any of: {sources:?}");
    }

    let bom: CDNBom = toml::from_str(&std::fs::read_to_string(&bom_path).unwrap()).unwrap();

    let mut out = String::from(
        "// @generated by build.rs from web/cdncache/bom.toml — do not edit.\n\
         pub struct CdnFile { pub served_as: &'static str, pub mime: &'static str, pub modified: u64, pub bytes: &'static [u8] }\n\
         pub static CDN_FILES: &[CdnFile] = &[\n",
    );
    for asset in &bom.asset {
        let path = cache_dir.join(&asset.target);
        if !path.exists() {
            let bytes = download(&asset.sources);
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            std::fs::write(&path, &bytes).unwrap();
        }
        println!("cargo:rerun-if-changed={}", path.display());

        let bytes = std::fs::read(&path).unwrap();
        assert_eq!(
            sha384(&bytes),
            asset.sha384,
            "{}: sha384 mismatch — remove the corrupt file and rebuild",
            path.display()
        );

        // The MIME type and mtime are what `static_files::Resource` needs in
        // order to be served; the extension of `served_as` is what the client
        // sees, so guess from that rather than from the on-disk target.
        let mime = mime_guess::from_path(&asset.served_as)
            .first_or_octet_stream()
            .to_string();
        let modified = std::fs::metadata(&path)
            .and_then(|m| m.modified())
            .ok()
            .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
            .map_or(0, |d| d.as_secs());

        out.push_str(&format!(
            "    CdnFile {{ served_as: {:?}, mime: {:?}, modified: {}, bytes: include_bytes!({:?}) }},\n",
            asset.served_as, mime, modified, path,
        ));
    }
    out.push_str("];\n");

    // `docgen` includes this module too, but only reads CDN_FILES.
    out.push_str(
        r#"
#[allow(dead_code)]
pub fn resources() -> ::std::collections::HashMap<&'static str, ::static_files::Resource> {
    CDN_FILES
        .iter()
        .map(|f| {
            (
                f.served_as,
                ::static_files::resource::new_resource(f.bytes, f.modified, f.mime),
            )
        })
        .collect()
}
"#,
    );

    std::fs::write(Path::new(out_dir).join("generated_cdn_cache.rs"), out).unwrap();
}
