FROM docker.io/library/debian:13.5

RUN apt-get update \
 && apt-get install -y --no-install-recommends python3 python3-venv \
 && rm -rf /var/lib/apt/lists/*

# Set up a venv to allow pip installs (debian uses externally managed Python).
RUN python3 -m venv /opt/verifier-venv
ENV PATH="/opt/verifier-venv/bin:$PATH"

COPY lib /tmp/lib
RUN pip install --no-cache-dir /tmp/lib && rm -rf /tmp/lib

CMD [ "bash" ]
