use documented::{Documented, DocumentedFields};
use id2202_autograder_macros::TestKind;
use schemars::JsonSchema;

use super::{discover_by_suffix, PostInit, PostInitCtx};
use crate::error::Error;

/// This test kind grades the solution using a multi-stage pipeline:
///
///  1. run the student binary to generate an assembly file,
///  2. assemble it,
///  3. compile it, then
///  4. run the compiled binary.
///
/// The output from each stage is checked along the way, only proceeding to the
/// next stage if the previous one was successful. The checking of stdout,
/// stderr, and exit codes follow the same semantics as for the `run` test
/// kind.
///
/// # Important
/// The maximum size of a generated assembly program is dictated by the
/// `max_output` test case setting.
///
/// For example, given the following test group:
///
/// ```text
/// my-group/
///   config.toml
///   genasm-example.test.toml
///   genasm-example.c
/// ```
///
/// Then in `genasm-example.test.toml`:
///
/// ```toml
/// [test]
/// kind = "gen_asm_and_run"
///
/// [test.options]
/// bin = "student-compiler"
/// args = ["--emit-x86_64"]
/// code = [0]
/// auto_input_files = [".c"]
///
/// assemble_cmd = ["nasm", "-felf64", "<ASM_FILE>", "-o", "sol.o"]
/// assemble_code = [0]
/// compile_cmd = ["gcc", "-no-pie", "sol.o", "-o", "sol.exe"]
/// compile_code = [0]
///
/// run_cmd = ["./sol.exe", "echo", "5"]
/// run_stdout = ["5\n"]
/// ```
///
/// This will copy the file `genasm-example.c` into the container, and provide
/// a path to it as a trailing argument when running the students solution.
/// This test will approximately be run as:
///
///  1. `/solution/student-compiler --emit-x86_64 PATH_TO_C_FILE > out.asm`
///  2. `nasm -felf64 ./out.asm -o sol.o`
///  3. `gcc -no-pie sol.o -o sol.exe`
///  4. `./sol.exe echo 5`
///
/// The semantics of the `run` test kind applies to the final stage, where
/// stdout, stderr, and exit code is captured, and then checked against valid
/// alternatives.
#[derive(JsonSchema, Debug, Clone, Documented, DocumentedFields, TestKind)]
#[testkind(ident = "gen_asm_and_run")]
pub struct GenASMAndRun {
    /// The student binary to execute in order to produce the assembly.
    pub bin: String,
    /// Arguments when executing `bin`.
    pub args: Vec<String>,
    /// Data piped to stdin when running the student binary.
    #[testkind(ignorable)]
    pub stdin: Option<String>,
    /// Acceptable exit codes after running the student binary.
    pub code: Vec<i32>,
    /// Expected output on stderr after running the student binary, matched
    /// against the whole captured stream. Must match at least one value in the
    /// list. An empty list allows any output.
    pub stderr: Vec<String>,
    /// Ignore leading and trailing whitespace characters when comparing the
    /// student binary's captured stderr against each expected value.
    pub stderr_trim: bool,
    /// Ignore all whitespace characters when comparing the student binary's
    /// captured stderr against each expected value. Takes precedence over
    /// `stderr_trim`.
    pub stderr_strip_whitespace: bool,
    /// Files to provide as input arguments when running the student binary.
    /// The files are copied into the container and given an autogenerated
    /// name inside the container. The paths to the generated files inside the
    /// container are then appended to the end of the command line arguments
    /// when running the student binary.
    ///
    /// If an input file is specfified with a relative path, its resolved to
    /// the config file which defined it.
    #[testkind(relpath)]
    pub input_files: Vec<String>,
    /// Suffixes for automatically discovering input files. A file in the test
    /// case's own directory named `<test name><suffix>` is appended to
    /// `input_files`, so `[".cpp"]` picks up `t01.cpp` for `t01.test.toml`, if
    /// `t01.cpp` is located in the same directory as the .test.toml file.
    pub auto_input_files: Vec<String>,

    /// Assembler command. An argument that is exactly `<ASM_FILE>` is
    /// replaced by the path to the generated assembly file.
    pub assemble_cmd: Vec<String>,
    /// Acceptable assembler exit codes.
    pub assemble_code: Vec<i32>,

    /// Compiler/linker command.
    pub compile_cmd: Vec<String>,
    /// Acceptable compiler exit codes.
    pub compile_code: Vec<i32>,

    /// Command to run the compiled binary.
    pub run_cmd: Vec<String>,
    /// Data piped to stdin of the compiled binary.
    #[testkind(ignorable)]
    pub run_stdin: Option<String>,
    /// Acceptable exit codes for the compiled binary.
    pub run_code: Vec<i32>,
    /// Expected output on stdout after running the compiled binary, matched
    /// against the whole captured stream. Must match at least one value in the
    /// list. An empty list allows any output. An empty list allows any output.
    pub run_stdout: Vec<String>,
    /// Ignore leading and trailing whitespace characters when comparing the
    /// compiled binary's captured stdout against each expected value.
    pub run_stdout_trim: bool,
    /// Ignore all whitespace characters when comparing the compiled binary's
    /// captured stdout against each expected value. Takes precedence over
    /// `run_stdout_trim`.
    pub run_stdout_strip_whitespace: bool,
    /// Expected output on stderr after running the compiled binary, matched
    /// against the whole captured stream. Must match at least one value in the
    /// list. An empty list allows any output. An empty list allows any output.
    pub run_stderr: Vec<String>,
    /// Ignore leading and trailing whitespace characters when comparing the
    /// compiled binary's captured stderr against each expected value.
    pub run_stderr_trim: bool,
    /// Ignore all whitespace characters when comparing the compiled binary's
    /// captured stderr against each expected value. Takes precedence over
    /// `run_stderr_trim`.
    pub run_stderr_strip_whitespace: bool,
}

impl PostInit for GenASMAndRun {
    fn post_init(&mut self, ctx: &PostInitCtx) -> Result<(), Error> {
        discover_by_suffix(&mut self.input_files, &self.auto_input_files, ctx)
    }
}
