use documented::{Documented, DocumentedFields};
use id2202_autograder_macros::TestKind;
use schemars::JsonSchema;

use super::{discover_by_suffix, PostInit, PostInitCtx};
use crate::error::Error;

/// Execute a binary and check its output against a set of predefined expected
/// values.
///
/// For example, this test configuration can be used to test a solution on
/// `./n_primes 10` against an expected output:
///
/// ```toml
/// [test]
/// kind = "run"
///
/// [test.options]
/// bin = "n_primes"
/// args = ["10"]
///
/// # This specifies that the run program must exit with code 0.
/// code = [0]
///
/// # There is only one allowed value, and stdout must match that. But we
/// # don't care about any whitespaces that the program outputs.
/// stdout = ["2,3,5,7,11,13,17,19,23,29"]
/// stdout_strip_whitespace = true
///
/// # Also don't care about stderr, any text there is accepted
/// stderr = []
/// ```
///
/// Example of checking whether output matches one of predefined outputs:
///
/// ```toml
/// [test]
/// kind = "run"
///
/// [test.options]
/// bin = "randint"
/// args = ["4"]
///
/// # Don't care about return code or stderr here
/// code = []
/// stderr = []
///
/// # `./randint 4` should generate a random integer in the range [0,4)
/// stdout = ["0", "1", "2", "3"]
/// stdout_trim = true
/// ```
#[derive(JsonSchema, Debug, Clone, Documented, DocumentedFields, TestKind)]
#[testkind(ident = "run")]
pub struct Run {
    /// Binary to execute.
    pub bin: String,
    /// Command-line arguments.
    pub args: Vec<String>,
    /// Optional text to write on stdin.
    #[testkind(ignorable)]
    pub stdin: Option<String>,
    /// Acceptable exit codes. If an empty list is provided, then any exit
    /// code is allowed.
    pub code: Vec<i32>,
    /// Expected output on stdout after running the binary, matched against the
    /// whole captured stream. Must match at least one value in the list. An
    /// empty list allows any output.
    pub stdout: Vec<String>,
    /// Ignore leading and trailing whitespace characters when comparing
    /// captured stdout against each expected value.
    pub stdout_trim: bool,
    /// Ignore all whitespace characters when comparing captured stdout
    /// against each expected value. Takes precedence over `stdout_trim`.
    pub stdout_strip_whitespace: bool,
    /// Expected output on stderr after running the binary, matched against the
    /// whole captured stream. Must match at least one value in the list. An
    /// empty list allows any output.
    pub stderr: Vec<String>,
    /// Ignore leading and trailing whitespace characters when comparing
    /// captured stderr against each expected value.
    pub stderr_trim: bool,
    /// Ignore all whitespace characters when comparing captured stderr
    /// against each expected value. Takes precedence over `stderr_trim`.
    pub stderr_strip_whitespace: bool,
    /// Files to provide as input arguments when running the binary. The files
    /// are copied into the container and given an autogenerated name inside
    /// the container. The paths to the generated files inside the container
    /// are then appended to the end of the command line arguments when running
    /// the binary.
    ///
    /// If an input file is specified with a relative path, it is resolved to
    /// the config file which defined it.
    #[testkind(relpath)]
    pub input_files: Vec<String>,

    /// Suffixes for automatically discovering input files. A file in the test
    /// case's own directory named `<test name><suffix>` is appended to
    /// `input_files`, so `[".cpp"]` picks up `t01.cpp` for `t01.test.toml`, if
    /// `t01.cpp` is located in the same directory as the .test.toml file.
    pub auto_input_files: Vec<String>,
}

impl PostInit for Run {
    fn post_init(&mut self, ctx: &PostInitCtx) -> Result<(), Error> {
        discover_by_suffix(&mut self.input_files, &self.auto_input_files, ctx)
    }
}
