use documented::{Documented, DocumentedFields};
use id2202_autograder_macros::TestKind;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

use super::{discover_by_suffix, PostInit, PostInitCtx};
use crate::error::Error;

/// Execute a binary and hand its stdout, stderr and exit code to a
/// course-provided verifier program, which decides whether the test passed.
///
/// # Note
/// This adds noticeable runtime overhead compared to the other test kinds, and
/// the defined scripts may introduce runtime bugs that cannot be checked by
/// the autograder. It is recommended to use test kind `run` where possible.
///
/// It is common to define a verifier for its test group, and only specialize
/// the parameters for a certain test case. For example given this test group:
///
/// ```text
/// my-group/
///   config.toml
///   t01.test.toml
///   t02.test.toml
///   verifier.py
/// ```
///
/// Then in `config.toml`:
///
/// ```toml
/// title = "My Group"
///
/// [test]
/// kind = "run_verifier"
///
/// [test.options]
/// bin = "graded-bin"
/// verifier_path = "./verifier.py"
///
/// [test.options.verifier_param_schema]
/// min_value = {type = "int", default = 0}
/// unbounded_max = {type = "bool", default = false}
/// ```
///
/// In `t01.test.toml`:
///
/// ```toml
/// # We set one custom parameter value to adjust the verifier for when running
/// # the test case with this argument to the compiled binary. The other
/// # `unbounded_max` argument will still be provided to the verifier, but
/// # using its default value.
/// [test.options]
/// args = ["custom-arg1"]
/// verifier_params.min_value = 1
/// ```
///
/// ... and in `t02.test.toml`:
///
/// ```toml
/// # Here we override both when grading output of `./graded-bin custom-arg2`.
/// [test.options]
/// args = ["custom-arg2"]
/// verifier_params.min_value = 3
/// verifier_params.unbounded_max = true
/// ```
///
/// The `verifier.py` script should ideally use the `autograder_verifier_tools`
/// package to read input and provide output. This wraps the underlying mode of
/// interaction between the runner and the verifier.
///
/// Once the graded execution (e.g. `./graded-bin custom-arg2`) has exited, the
/// autograder will provide a JSON object on standard input to the verifier
/// script:
///
/// ```json
/// {
///     "cmd": ["./graded-bin", "custom-arg2"],
///     "code": 0,
///     "stdout": {"enc": "utf8", "data": "the text on stdout"},
///     "stderr": {"enc": "utf8", "data": ""},
///     "files": {},
///     "params": {
///         "min_value": 3,
///         "unbounded_max": true
///     }
/// }
/// ```
///
/// `cmd` is the full command line that was used to run the graded solution.
/// Any files that were provided as command line arguments have their names
/// mapped to their contents in the `files` field.
///
/// The autograder then expects the verifier to write its verdict as a JSON
/// object on standard output, and nothing else, and to exit with code 0. Use
/// stderr for debugging output if necessary. Example verdict from the verifier
/// when the test case was accepted:
///
/// ```json
/// {"accepted": true, "reason": null}
/// ```
///
/// `reason` may be omitted or `null` when the test case is accepted. Only
/// `accepted` is required.
///
/// If the verifier rejected the output from the graded program:
///
/// ```json
/// {
///     "accepted": false,
///     "reason": "The decoded value is below the allowed minimum."
/// }
/// ```
#[derive(JsonSchema, Debug, Clone, Documented, DocumentedFields, TestKind)]
#[documented(trim = false)]
#[testkind(ident = "run_verifier")]
pub struct RunVerifier {
    /// Binary to execute.
    pub bin: String,
    /// Command-line arguments.
    pub args: Vec<String>,
    /// Optional text to write on stdin.
    #[testkind(ignorable)]
    pub stdin: Option<String>,
    /// Files to provide as input arguments when running the binary. The files
    /// are copied into the container and given an autogenerated name inside
    /// the container. The paths to the generated files inside the container
    /// are then appended to the end of the command line arguments when running
    /// the binary.
    ///
    /// If an input file is specified with a relative path, it is resolved to
    /// the config file which defined it.
    #[testkind(relpath)]
    pub input_files: Vec<String>,
    /// Suffixes for automatically discovering input files. A file in the test
    /// case's own directory named `<test name><suffix>` is appended to
    /// `input_files`, so `[".cpp"]` picks up `t01.cpp` for `t01.test.toml`, if
    /// `t01.cpp` is located in the same directory as the .test.toml file.
    pub auto_input_files: Vec<String>,

    /// Path to the verifier program. Must be a Python 3 file ending in `.py`.
    #[testkind(relpath, clears(verifier_params, verifier_param_schema))]
    pub verifier_path: String,

    /// Parameters passed to the verifier, merged key by key down the tree. Each
    /// one has to be declared in `verifier_param_schema`.
    #[testkind(merge = "deep")]
    pub verifier_params: BTreeMap<String, ParamValue>,

    /// Parameters the verifier accepts, declared alongside `verifier_path`.
    pub verifier_param_schema: BTreeMap<String, ParamSpec>,

    /// Seconds a single run of the verifier may take. Exceeding it is an
    /// autograder error, not a failed test case. This setting is about
    /// catching a broken verifier rather than a slow solution.
    pub verifier_timeout: u32,
}

/// A verifier parameter value. Only these three types cross the boundary into
/// the verifier, so the wire format stays trivially representable in JSON.
#[derive(Serialize, Deserialize, JsonSchema, Debug, Clone, PartialEq)]
#[serde(untagged)]
#[schemars(title = "ParamValue")]
pub enum ParamValue {
    Bool(bool),
    Int(i64),
    Str(String),
}

impl ParamValue {
    fn type_name(&self) -> &'static str {
        match self {
            Self::Bool(_) => "bool",
            Self::Int(_) => "int",
            Self::Str(_) => "str",
        }
    }
}

/// The declaration of a single verifier parameter.
#[derive(Deserialize, JsonSchema, Debug, Clone)]
#[serde(deny_unknown_fields)]
#[schemars(title = "ParamSpec")]
pub struct ParamSpec {
    /// One of `bool`, `int` or `str`.
    #[serde(rename = "type")]
    pub ty: ParamType,

    /// Value used when a test case does not set the parameter. Without one the
    /// parameter is required.
    pub default: Option<ParamValue>,
}

#[derive(Deserialize, JsonSchema, Debug, Clone, Copy, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum ParamType {
    Bool,
    Int,
    Str,
}

impl ParamType {
    fn accepts(&self, value: &ParamValue) -> bool {
        matches!(
            (self, value),
            (Self::Bool, ParamValue::Bool(_))
                | (Self::Int, ParamValue::Int(_))
                | (Self::Str, ParamValue::Str(_))
        )
    }

    fn name(&self) -> &'static str {
        match self {
            Self::Bool => "bool",
            Self::Int => "int",
            Self::Str => "str",
        }
    }
}

impl PostInit for RunVerifier {
    fn post_init(&mut self, ctx: &PostInitCtx) -> Result<(), Error> {
        discover_by_suffix(&mut self.input_files, &self.auto_input_files, ctx)?;

        let path = &self.verifier_path;
        if !std::path::Path::new(path).is_file() {
            return Err(Error::test_config_msg(format!("verifier \"{path}\" is not a file")).into());
        }
        if !path.ends_with(".py") {
            return Err(Error::test_config_msg(format!(
                "verifier \"{path}\" has no supported suffix, expected \".py\""
            ))
            .into());
        }

        self.resolve_params()
    }
}

impl RunVerifier {
    /// Checks every parameter against the schema and fills in the defaults, so
    /// that the verifier always receives a complete set.
    fn resolve_params(&mut self) -> Result<(), Error> {
        for (name, value) in self.verifier_params.iter() {
            let spec = self.verifier_param_schema.get(name).ok_or_else(|| {
                Error::test_config_msg("parameter is not declared in verifier_param_schema")
                    .key(name)
            })?;
            if !spec.ty.accepts(value) {
                return Err(Error::test_config_msg(format!(
                    "expected {}, got {}",
                    spec.ty.name(),
                    value.type_name()
                ))
                .key(name)
                .into());
            }
        }

        for (name, spec) in self.verifier_param_schema.iter() {
            if self.verifier_params.contains_key(name) {
                continue;
            }
            let default = spec.default.clone().ok_or_else(|| {
                Error::test_config_msg("parameter has no default and was not set").key(name)
            })?;
            if !spec.ty.accepts(&default) {
                return Err(Error::test_config_msg(format!(
                    "default is {}, expected {}",
                    default.type_name(),
                    spec.ty.name()
                ))
                .key(name)
                .into());
            }
            self.verifier_params.insert(name.to_owned(), default);
        }

        Ok(())
    }
}
